# This is a comment
name: Test Cell

# Diffusion and spot motion simulation options

# Diffusion options:
#   Initialization:
#       start: uniform - generates all spots from a uniform distribution across the cell
#       start: gaussian_point - generates all spots from a 2D gaussian about a point
#           parameters: [(x,y),(sigma_x, sigma_y)]
diffusion:

    initialization:         # how to initalize the spots?
        start: uniform      # uniform distribution start, no parameters
        parameters: []
        
    motion:                             # brownian motion options
        diffusion_coefficient: 1.0      # diffusion coefficient(s) for spots
        tstep: 1.0                      # time step size for brownian motion
        elasticity: 1.0                 # elastic boundary reflections, 1 = 100% elastic no momentum loss.
        
        
    jitter:                             # jitter the spot locations across channels (simulates probe subpixel changes)
        use: True
        n_channels: 3                   # number of channels to generate via jittering
        method: registration            # method by which to jitter, gaussian is default with parameters = [sigma]
        parameters: 
            - (0,0)
            - (2,2)
            - (-2,-2)               # parameters to jitter
        
    simulate_z:                         # simulate intensity loss due to brownian motion in Z
        use: False
        method: gaussian                # gaussian curve of intensity loss, scaled by sigma and min dimming
        parmaeters: [0.3]               # sigma of the gaussian curve, 
                                        # 0.3 is a smooth scaling to the edge of the z plane, losing 95% of intensity at z plane edge. 
                                        # .1 is losing all intensity 20% from center
                                        # .2 is losing all intensity 60% from center
        z_stack: 130                    # z_stack dimensions in nm
        min_dimming: 0.3                # minimum dimming intensity mod, this is the min multiplier
        

# Background image generation options

frame:
    quantile: .95                       # quantile to calculate standard dev of the pixels from 
    spot_size: 15     #size of the kernel
    
    channel 0:
        background:
            source: 0                   # which channel of the base video to use, 0 or 1 currently
            method: gaussian            # method for generating new frames, default gaussian fit of each pixel
            parameters: [1]             # parameters for generation: for gaussian this is the scale of the standard dev of the pixels
        
        spots:                          # spot options in this channel
            sigma: 2                    # sigma of the gaussian kernel of the spot
            intensity_scale: 10         # intensity scale to multiply the spot values by
            poisson_sample_spot: True   # sample from the kernel's poisson N photons
            photon_count: 1000          # how many photons to sample, lower = more static and pixely spot]
            
        photobleaching:                 # photobleaching options for this channel
            use: True
            method: 'normal_percent_loss'   # photobleaching method for this channel
            parameters: [0.01, 0.001]     # photobleaching parameters for this channel
                
       
    channel 1:
        background:
            source: 0
            method: gaussian
            parameters: [1]
        spots:
            sigma: 2
            intensity_scale: 10
            poisson_sample_spot: True
            photon_count: 2000
        photobleaching:
            use: True
            method: 'normal_percent_loss'
            parameters: [0.01, 0.001]
                
        
    channel 2:
        background:
            source: 1
            method: gaussian
            parameters: [1.1]
        spots:
            sigma: 2
            intensity_scale: 50
            poisson_sample_spot: True
            photon_count: 2000
        photobleaching:
            use: True
            method: 'normal_percent_loss'
            parameters: [0.01, 0.001]
                
            
mRNAs:
    model: default
    gene_file: 'Bactin_withTags.txt'
    burnin: 1000
    parameters: [0.03, 10, 10]
    use_precomputed_intensities: True
    precomputed_intensities_file: '../Databases/example_intensities_50.npy'



